client_id:
  
client_secret:
  
filepath:
  C:/Users/Kanan/Desktop/Taskilled/Capstone Project/Data/spotify_music_data.csv
  
singers_tracks:
 Halsey:
 - Without Me
 - Closer
 - The Tradition
 - Bells in Santa Fe
 - Easier than Lying
 - Lilith
 - Girl is a Gun
 - You asked for this
 - Darling
 - honey
 - Whispers
 - I am not a woman, I'm a God
 - The Lighthouse
 - Nightmare
 - People disappear here
 - Eyes Closed
 - Heaven In Hiding
 - Alone
 - Now Or Never
 - Sorry
 - Good Mourning
 - Lie
 - Walls Could Talk
 - Bad At Love
 - Strangers
 - Angel On Fire
 - Devil In Me
 - Hopeless
 - Castle
 - Hold Me Down
 - New Americana
 - Drive
 - Hurricane
 - Roman Holiday
 - Colors
 - Strange Love
 - Coming Down
 - Haunting
 - Control
 - Young God
 - Trouble
 - Ghost
 - Gasoline
 - Is There Somewhere
 - Ashley
 - clementine
 - Graveyard
 - You should be sad
 - I HATE EVERYBODY
 - 3AM

 Rauf & Faik:
 - ALONE AGAIN
 - Wonderful
 - Memories
 - Ramadan
 - Rubicon
 - Lonely
 - Animal
 - LUV

 Irmak Arıcı:
 - Mesele
 - Gönlümdeki Hain
 - Asık Suratım
 - Yağmurum Ol
 - Mühür
 - Güya
 - Nasıl Olacak
 - Kim Haklı
 
 Hiss: 
 - Bir Ömrün Nəğməsi
 - Kəpənəklər
 - Istəmirəm
 - Unuduram
 - Qorxuram
 - Biri Var
 - Zəng Elə
 - Cəsarət
 - Monoton
 - Sayıram
 - Sevdim
 - Busan
 - Karma
 - Mars
 - Şans
 - Bela
 - Çek
 - Get

 Ayaz Babayev:
 - Nə üçün belə
 - Ay Tənli Qadın
 - Xəyallar Fəsli
 - Sən Mənlə
 - Yaxşı Ki Varsan
 - Möcüzə
 - İmdat
 - Qara Gözlər
 - Yenəmi Sən
 - Uzaq Ol Ondan

 Nuri Serinlendirici:
 - Bir Gün
 - Gozleyirem
 - Taksi
 - Darixdim
 - Icime Atiyorum Ask
 - Kolge
 - O Gozel Xanimdi
 - Heyatima Xos Geldin
 - Hamı Bizdən Danışır
 - Sevdiyim
 - Sevdim
 - Hemise Toyda
 - Urek
 - Biri Var
 - Şərab
 - Xanimsan
 - Yubanma Gəl
 - Avara
 - Vətən
 - Nagilimsan
 - Bacara Bilmirem
 - Son Defe Gel
 - Yasat Meni
 - Vay Aman Has
 - Ayrılıgın Dogum Günü
 - Esq Delisi
 - Menimsen
 - Beyaz Gulum
 - Vagzali Sedasi
 - Oyna-Oyna
 - Pismanim
 - Birtanem
 - Cicekler
 - Can Ay Can
 - Etiraf

 Gazapizm:
 - Dayan
 - Çöplük
 - Pisliğin Üstüne Basmışlar
 - Yol
 - Perişan
 - Sağı Solu Kes
 - Yaşanırsa Diye
 - Bu Rüya Benim
 - Efkar
 - Unutulacak dünler
 - Bir Gün Her Şey
 - Gece Sabahın
 - Bağır
 - Paranı Kovala
 - Hakikatler
 - İsminizi İstiyorlar
 - Kalk Yataktan
 - Memleketsiz
 - Zanı
 - Yok
 - Yeraltı Edebiyatı
 - Kafandaki Silah
 - Kayıp Kelimeler
 - Olmaz İşte
 - Sanki Bir Halkın
 - İnsanlar Ölü
 - Borandan
 - Korkma
 - Argo
 - Kafam Karışıyor
 - Olur Mu
 - İzaf
 - Dünya Bu
 - Karanfil
 - Kayıp
 - Ölüler Dirilerden Çalacak
 - Kalbim Çukurda
 - Heyecanı Yok
 - Pusula

 Jacob's Piano:
 - Light
 - Snowdrops
 - Curabitur
 - New Era
 - Darling
 - Remember You
 - Experience
 - Giorni Dispari
 - Una Mattina
 - Nuvole Bianche
 - Fly
 - Oltremare
 - Divenire
 - I Giorni
 - Le Onde
 - Night
 - Primavera
 - Spheres
 - Rising
 - A Rainy Journey
 - Reverie
 - Snowing
 - O Holy Night
 - O Come All Ye Faithful
 - Monday
 - Jardin
 - Petrichor
 - Levitate
 - Psithurism
 - saman
 - Ballade Pour Adeline
 - Her
 - Emotions
 - Balcony Birds
 - Light of the Seven
 - On the Nature of Daylight
 - Autumn Breeze
 - Remembrance
 - Wandering
 - Thoughts
 - Horizon
 - Arrival of the Birds
 - Goodbye
 - Alone
 - Dreams
 - River Flows in You
 - Kiss the Rain
 - A Letter
 - May be
 - Porz Goret
 - Penn ar Lann
 - Pern
 - Moments
 - Colors of the Mind
 - Grieving Times
 - A Simple Melody

 Beyonce:
 - COZY
 - ALIEN SUPERSTAR
 - CUFF IT
 - BREAK MY SOUL
 - CHURCH GIRL
 - PLASTIC OFF THE SOFA
 - HEATED
 - THIQUE
 - ALL UP IN YOUR MIND
 - AMERICA HAS A PROBLEM
 - PURE/HONEY
 - SUMMER RENAISSANCE
 - BIGGER
 - FIND YOUR WAY BACK
 - NILE
 - ALREADY
 - OTHERSIDE
 - BLACK PARADE
 - Welcome
 - Crazy In Love
 - Freedom
 - Formation
 - So Much Damn Swag
 - Sorry
 - Kitty Kat
 - Bow Down
 - I Been On
 - Drunk in Love
 - Diva
 - Top Off
 - Party
 - I Care
 - Partition
 - Yonce
 - Mi Gente
 - Baby Boy
 - Hold Up
 - Countdown
 - Check On It
 - Get Me Bodied
 - Love On Top
 - Before I Let Go
 - Pray You Catch Me
 - Hold Up
 - Daddy Lessons
 - Love Drought
 - Sandcastles
 - Forward
 - All Night
 - Formation
 - Pretty Hurts
 - Haunted
 - Blow
 - No Angel
 - Partition
 - Jealous
 - Rocket
 - Mine
 - XO
 - Superpower
 - Heaven
 - Blue
 - Ring Off
 - I Miss You
 - Dance for You
 - I Care
 - Rather Die Young
 - End of Time
 - Best Thing I Never Had
 - Start Over
 - I Was Here
 - Naughty Girl
 - Freakum Dress
 - Smash Into You
 - Ave Maria
 - Radio
 - Ego
 - Hello
 - Baby Boy
 - Irreplaceable
 - Bootylicious
 - Upgrade U
 - Say My Name
 - At Last
 - Single Ladies
 - If I Were A Boy
 - Disappear
 - Satellites
 - Sweet Dreams
 - Scared of Lonely
 - Beautiful Liar
 - Green Light
 - Flaws and All
 - World Wide Woman
 - If
 - Suga Mama
 - Deja Vu
 - Ring The Alarm
 - Resentment
 - Listen
 - Be With You
 - Yes
 - Signs
 - Speechless
 - Gift from Virgo
 - Work It Out

 Billie Eilish:
 - Getting Older
 - Billie Bossa Nova
 - my future
 - Oxytocin
 - GOLDWING
 - Lost Cause
 - Not My Responsibility
 - OverHeated
 - Everybody Dies
 - Your Power
 - NDA
 - Therefore I Am
 - Happier Than Ever
 - Male Fantasy
 - bad guy
 - xanny
 - you should see me in a crown
 - all the good girls go to hell
 - wish you were gay
 - my strange addiction
 - bury a friend
 - ilomilo
 - listen before I go
 - i love you
 - goodbye
 - No Time To Die
 - everything i wanted
 - come out and play
 - bitches broken hearts
 - COPYCAT
 - my boy
 - watch
 - party favor
 - bellyache
 - ocean eyes
 - hostage
 - Bored
 - Six Feet Under

 Sam Smith:
 - Gloria
 - No God
 - Hurting Interlude
 - Lose You
 - Perfect
 - Unholy
 - How To Cry
 - Six Shots
 - Gimme
 - Who We Love
 - Diamonds
 - Dancing With A Stranger
 - Promises
 - Too Good At Goodbyes
 - Lay Me Down
 - My Oasis
 - Time After Time
 - How Do You Sleep?
 - For the Lover That I lost
 - Kids Again
 - Love Goes
 - Stay With Me
 - Young
 - Another One
 - So Serious
 - Dance
 - Breaking Hearts
 - Forgive Myself
 - To Die For
 - Fire On Fire
 - Say It First
 - One Last Song
 - Midnight Train
 - Burning
 - Him
 - Baby, You Make Me Crazy
 - No Peace
 - Palace
 - Pray
 - Nothing Left For You
 - The Thrill Of It All
 - Scars
 - One Day At A Time
 - Money On My Mind
 - Good Thing
 - Leave Your Lover
 - Like I Can
 - Life Support
 - Not In That Way
 - Restart
 - Latch
 - La La La
 - Make It To Me
 - Love Is A Losing Game
 - Nirvana
 - How Will I Know
 - Omen
 - Together

 Evgeny Grinko:
 - Things From The Past
 - On The Waves
 - Velvet Elephant
 - See You Tomorrow
 - Grass, Dew and Marmalade
 - Petrel Bird
 - Tomorrow
 - Where Art Thou
 - Dusty Room
 - Someone Who Forgot His Watch
 - Short Memory
 - Man In Old Rumpled Hat
 - G-Dur
 - Unexpected Finale Somewhere in Lisbon
 - Once Upon a Time
 - Carousel
 - Where
 - Hunter in Love
 - Noir
 - Valse
 - Serenade
 - Time, Backward!
 - Eastern Serenade
 - Rumba
 - Ice for Aureliano Buendia
 - Lullaby for Yasha
 - Lullaby for Erik
 - And I Blew out the Candles
 - Gull Song
 - Wind Brought
 - Cold Morning
 - Jane Maryam
 - Separation
 - Valse Cm
 - Sail on the Roof
 - Winter Sunshine
 - Other Child Room
 - It Smells Like Chamomile Tea
 - Blizzard
 - Sunset
 - Spring Drops
 - Field
 - Poirot
 - Wake Up

 Dua Lipa:
 - Future Nostalgia
 - Cool
 - Physical
 - Levitating
 - Pretty Please
 - Hallucinate
 - Love Again
 - Break My Heart
 - Good in Bed
 - Boys Will Be Boys
 - Fever
 - That Kind Of Woman
 - Not My Problem
 - Kiss and Make Up
 - Genesis
 - Lost In Your Light
 - Hotter Than Hell
 - Be the One
 - IDGAF
 - Blow Your Mind
 - Garden
 - No Goodbyes
 - New Rules
 - Begging
 - Homesick
 - Dreams
 - Room for 2
 - New Love
 - Bad Together
 - Last Dance
 - Want To
 - Running

 Rihanna:
 - Consideration
 - James Joint
 - Kiss It Better
 - Work
 - Desperado
 - Woo
 - Needed Me
 - Yeah, I Said It
 - Never Ending
 - Love On The Brain
 - Higher
 - Close To You
 - Goodnight Gotham
 - Pose
 - Sex With Me
 - Phresh Out The Runway
 - Diamonds
 - Numb
 - Pour It Up
 - Jump
 - Right Now
 - What Now
 - Stay
 - Get It Over With
 - No Love Allowed
 - Lost In Paradise
 - Half Of Me
 - You Da One
 - Where Have You Been
 - Talk That Talk
 - Cockiness
 - We All Want Love
 - Drunk On Love
 - Roc Me Out
 - Farewell
 - Red Lipstick
 - Do Ya Thang
 - Fool In Love
 - S&M
 - Cheers
 - Fading
 - Only Girl
 - California King Bed
 - Man Down
 - Raining Men
 - Complicated
 - Skin
 - Mad House
 - Wait Your Turn
 - Hard
 - Stupid In Love
 - ROCKSTAR 101
 - Russian Roulette
 - Fire Bomb
 - Rude Boy
 - Photographs
 - G4L
 - Te Amo
 - Cold Case Love
 - The Last Song
 - Umbrella
 - Push Up On Me
 - Shut Up And Drive
 - Hate That I Love You
 - Say It
 - Sell Me Candy
 - Lemme Get That
 - Rehab
 - Question Existing
 - Good Girl Gone Bad
 - Disturbia
 - Take A Bow
 - SOS
 - Unfaithful
 - We Ride
 - Final Goodbye
 - Break It Off
 - Crazy Little Thing Called Love
 - Selfish Girl
 - Girl Like Me
 - A Million Miles Away
 - Pon De Replay
 - Here I Go Again
 - Willing To Wait
 - Music Of The Sun
 - Let Me
 - Rush
 - Now I Know

 Charlie Puth:
 - Charlie Be Quiet!
 - Light Switch
 - Smells Like Me
 - Left and Right
 - Loser
 - Marks On My Neck
 - Tears On My Piano
 - No More Drama
 - The Way I Am
 - Attention
 - LA Girls
 - How Long
 - Done for Me
 - Patient
 - If You Leave Me Now
 - BOY
 - Slow It Down
 - Change
 - Somebody Told Me
 - Empty Cups
 - Through It All
 - One Call Away
 - Dangerously
 - Marvin Gaye
 - Losing My Mind
 - My Gospel
 - Up All Night
 - Left Right Left
 - Suffer
 - As You Are
 - Some Type of Love
 - See You Again
 - River
 - Does It Feel
 - Nothing But Trouble

 Hauser:
 - Sway
 - La Isla Bonita
 - Quando Quando Quando
 - Cherry Pink and Apple Blossom White
 - Senorita
 - Besame Mucho
 - Obsesion
 - Historia de un Amor
 - Waka Waka
 - Swan Lake
 - Nocturno

 Dharia:
 - Sugar & Brownies
 - August Diaries
 - Tara Rita

 Mustafa Ceceli:
 - Kıymetlim
 - Zincirimi Kırdı Aşk
 - Peşindeyim
 - Ayşe
 - İyi Ki Hayatımdasın
 - Can Parçam
 - Söz Aramam
 - Hikaye
 - Anmam
 - Leyla
 - Maşallah
 - Aşk Adına
 - Topla
 - Ömrümüzün Baharı
 - Bir Zamanlar Deli Gönlüm
 - Dünyanın Bütün Sabahları
 - Gel De Sen Konuş
 - Rahat Rahat
 - Oyun Olmazdı Aşkla
 - Sevgilim
 - Es
 - Zillerime Basıp Kaçıyor
 - Aman
 - Bir Yanlış Kaç Doğru?
 - Alametifarika
 - Aşk Döşeği
 - Gizli
 - Aşikardır Zat-ı Hak
 - Hata
 - Bana Uyar
 - Gidersen
 - Neme Lazım
 - Kanaryam
 - Şarkı
 - Kendimce
 - Söz Veremem
 - Bekle
 - Dön
 - Tenlerin Seçimi
 - Limon Çiçekleri
 - Hüsran
 - İslak İmza
 - Aşkım Benim
 - Pervane
 - İlle De Aş
 - Kiraz
 - Gül Rengi
 - Ah Yıllar
 - Askersin
 - 17 Milyon
 - Kalpten
 - Alem Güzel
 - Kucak Kucak
 - Al Götür Beni
 - Eksik
 - Aşk İçin Gelmişiz
 - Sultanım
 - Kainatın Aynasıyım
 - Severim Ben Seni
 - Sevgi Baht Olmuş
 - Can Ellerinden Gelmişem
 - Hepsi Gelir Geçer
 - Derviş Bağrı Taş Gerek
 - Ben Yürürüm Yane Yane
 - Kar Etmez Ahım
 - Sevdim Seni Mabuduma
 
 Post Malone:
 - Feeling Whitney
 - Money Made Me Do It
 - Up There
 - Too Young
 - Feel
 - Go Flex
 - Patient
 - Cold
 - Deja Vu
 - Big Lie
 - Broken Whiskey Glass
 - White Iverson
 - Congratulations
 - I Fall Apart
 - Psycho
 - Better Now
 - Circles
 - Chemical
 - Reputation
 - Cooped Up
 - Lemon Tree
 - Wrapped Around Your Finger
 - I Like You
 - I Cannot Be
 - Insane
 - Love/Hate Letter To Alcohol
 - Wasting Angels
 - Euthanasia
 - Waiting For A Miracle
 - One Right Now
 - Waiting For Never
 - Hateful
 - Saint-Tropez
 - Enemies
 - Allergic
 - A Thousand Bad Times
 - Die For Me
 - On The Road
 - Take What You Want
 - Staring At The Sun
 - Internet
 - Goodbyes
 - Myself
 - I Know
 - Wow.
 - Paranoid
 - Spoil My Night
 - Rich & Sad
 - Zack and Codeine
 - Over Now
 - Ball For Me
 - Otherside
 - Blame It On Me
 - Same Bitches
 - Jonestown
 - 92 Explorer
 - Candy Paint
 - Sugar Wraith
 - Yours Truly, Austin Post
 - Leave
 - Hit This Hard
 
 Katy Perry:
 - Fingerprints
 - Self Inflicted
 - Lost
 - If You Can Afford Me
 - Hot N Cold
 - Ur So Gay
 - Mannequin
 - Thinking Of You
 - Waking Up In Vegas
 - I Kissed A Girl
 - One Of The Boys
 - Wide Awake
 - Part Of Me
 - The One That Got Away
 - Not Like Movies
 - Hummingbird Heartbeat
 - Pearl
 - Who Am I Living For?
 - E.T.
 - The One That Got Away
 - Circle The Drain
 - Peacock
 - Firework
 - California Gurls
 - Last Friday Night
 - Teenage Dream
 - Choose Your Battles
 - It Takes Two
 - Spiritual
 - By The Grace Of God
 - Double Rainbow
 - This Moment
 - Love Me
 - Ghost
 - International Smile
 - This Is How We Do
 - Dark Horse
 - Unconditionally
 - Walking On Air
 - Birthday
 - Legendary Lover
 - Roar
 - Act My Age
 - Dance With The Devil
 - Never Really Over
 - Cry About It Later
 - Teary Eyes
 - Daisies
 - Resilient
 - Not the End of the World
 - Smile
 - Champagne Problems
 - Tucked
 - Harleys in Hawaii
 - Only Love
 - What Makes A Woman
 - Witness
 - Roulette
 - Hey Hey Hey
 - Swish Swish
 - Power
 - Mind Maze
 - Miss You More
 - Chained To The Rhythm
 - Tsunami
 - Bon Appetit
 - Bigger Than Me
 - Save As Draft
 - Pendulum
 - Into Me You See
 
 Mark Eliyahu:
 - Brothers Getting Together
 - Lion of Judea
 - Chant to the Observer in Sunset
 - The Northern Star
 - Nostalgy
 - Humbleness
 - Prayer
 - The Magnificent Nine
 - Coming Back
 - Impro Esfahan
 - The Firebird
 - Shur Ve Habit
 - I Will Seek For You At Dawn
 - Nigun Nava
 - Sands
 - Krav Shtiya
 - Ballad For The Weeping Spring
 - Longings
 - Journey
 - Caravan
 - Tribe
 - Gulbahar
 - Traveler
 - Through Me
 - Temptation
 - Night Train
 - Drops
 - Flood Dance
 - Roads
 - Thunder
 - Tinnitus
 - Stress
 - Slow Voltage
 - Memories
 - Makot
 - Saba
 - Piris Shur
 - Nostalgic
 - Drone Piris
 - Emotional Teheran
 - Peyote
 - LSD
 - Endless
 - Hope
 - Open Sky
 - Sunshine
 - About Love
 - Derinlerde
 - Do You Remember
 - Daydream
 - Wind
 - Mahur
 - With You
 - Silence
 - The Run Away
 - Tehran
 - Hame Azad
 
 Houssem Amari:
 - La Notte
 - Ma Reine
 - Khamsa
 - Safir
 - Voyage
 - Dalia
 - El Bandido
 - Por Ti
 
 Ava Max:
 - Sweet But Psycho
 - Salt
 - So Am I
 - Rumors
 - Belladonna
 - Born To The Night
 - Call Me Tonight
 - Tattoo
 - Naked
 - Kings & Queens
 - H.E.A.V.E.N
 - My Head & My Heart
 - Million Dollar Baby
 - Sleepwalker
 - Ghost
 - Hold Up
 - Weapons
 - Diamonds & Dancefloors
 - In The Dark
 - Turn Off The Lights
 - One Of Us
 - Get Outta My Heart
 - Cold As Ice
 - Last Night On Earth
 - Born to the Night
 - Torn
 - Take You To Hell
 
 Alan Walker:
 - Faded
 - Diamond Heart
 - Alone
 - Darkside
 - All Falls Down
 - Sing Me To Sleep
 - Interlude
 - Different World
 - Do It All for You
 - Lonely
 - Lily
 - Lost Control
 - Not You
 - OK
 - Heading Home
 - Drone Wars
 - World We Used To Know
 - On My Way
 - Fake A Smile
 - Sorry
 - Out Of Love
 - Paradise
 - Shut Up
 - Ritual
 - The Drum
 - Lovesick
 - Catch Me If You Can
 - Blue
 - Somebody Like U
 - Extremes
 - Hello World
 - Adventure Time
 - Time
 - Man On The Moon
 - Alone
 - Red Nexus Rising
 
 Maroon 5:
 - Infatuation
 - Woman
 - Secret
 - Better That We Break
 - Not Falling Apart
 - Goodnight Goodnight
 - Little Of Your Time
 - Harder To Breathe
 - Shiver
 - She Will Be Loved
 - This Love
 - Makes Me Wonder
 - Sunday Morning
 - Wake Up Call
 - If I Never See Your Face Again
 - No Curtain Call
 - Last Chance
 - Out Of Goodbyes With Lady Antebellum
 - Runaway
 - Just A Feeling
 - Get Back In My Life
 - How
 - Hands All Over
 - Stutter
 - Give A Little More
 - Misery
 - Wipe Your Eyes
 - Beautiful Goodbye
 - Tickets
 - Sad
 - Fortune Teller
 - Lady Killer
 - Love Somebody
 - The Man Who Never Lied
 - Lucky Strike
 - Day Light
 - Payphone
 - One More Night
 - Sex and Candy
 - Shoot Love
 - This Summer
 - My Heart Is Open
 - Feelings
 - Coming Back For You
 - New Love
 - In Your Pocket
 - Leaving California
 - Sugar
 - Unkiss Me
 - It Was Always You
 - This Love
 - Maps
 - Daylight
 - Animals
 - Moves Like Jagger
 - Cold
 - Plastic Rose
 - Visions
 - Denim Jacket
 - Closure
 - Girls Like You
 - Whiskey
 - Who I Am
 - Help Me Out
 - Bet My Heart
 - Lips On You
 - Wait
 - What Lovers Do
 - Best 4 U
 - Beautiful Mistakes
 - Lost
 - Echo
 - Lovesick
 - Remedy
 - Seasons
 - One Light
 - Convince Me
 - Memories
 - Button
 - Lifeestyle
 
 Billy Esteban:
 - Dilala
 - Sama Moma
 - My Freedom
 - Into the Blue
 - Glorija
 - Dream
 - Samuil
 - Awakening
 - Aliman
 - Rain Girl
 - Izrael
 - Forest
 - Rosa Rosi
 - First Snow
 - Desert Girl
 - Night in Bosphorus
 - A Book of the Sea
 - Amazon
 - Night Experience
 - Oro
 - Blazena Gora
 - Road to Istanbul
 - Winds Melody
 - The Gates of Istanbul
 - Red Sun
 - Kolkota Taxi
 - Buddha
 - Eternity
 - Cosmik Sitar
 - Balkan Woman
 - Starry Field
 - Sansula
 - Secret Mountain
 - Ascension
 - Namaste
 - Call to the Divine
 - Game of Butterflies
 - Message
 - Moment of Peace
 - Coffee Time
 - Five Guitars
 - Casablanca
 - Eagea Sunset
 - Sunset in Anatolia
 - Ederlezi
 - Si Zaljubiv
 - Amor
 - Caravan Tribe
 - Souvenir from Sea
 - Secret Stories
 - Gipsy Spring
 - Alchemy
 - Dubai Night
 - Gipsy Melody
 - Good Morning Istanbul
 - Time To Change
 - Sevda
 - Mihrimah
 - Night In Istanbul
 - Light Of The Moon
 - Andalusian Woman
 - The Walk Of The Sultan
 - Mediterranean Sunset
 - Song For Monica
 - Rumelia
 - Princess of Persia
 - Arabian Eyes
 - Dance With Me
 - Passion
 - Petra
 - World
 - Obsession
 - Anuska Dream
 - Katerina
 - Bay Nikola
 - Pustiya
 - Sevdelinke
 - Mace Mace
 - Halkidiki
 - Lunar
 - Mediterraneo
 - Eagea
 - Ozora